### ISSUE TITLE
Unable to load model error still occurring

### ISSUE THREAD

**Issue by uptogodown** [vicuna-tools/vicuna-installation-guide#14]
Still getting the "unable to load model error", I am on Linux Mint latest version using the one setp install script:

git clone https://github.com/fredi-python/llama.cpp.git && cd llama.cpp && make -j && cd models && wget -c https://huggingface.co/eachadea/ggml-vicuna-13b-1.1/resolve/main/ggml-vic13b-uncensored-q5_1.bin

After it has completed it's install I go to use Vicuna

Command:
~/llama.cpp$ ./main -m ggml-vic13b-uncensored-q5_1.bin -f 'prompts/chat-with-vicuna-v1.txt' -r 'User:' --temp 0.36

Output:
main: build = 632 (787aadf)
main: seed  = 1687195202
error loading model: failed to open ggml-vic13b-uncensored-q5_1.bin: No such file or directory
llama_init_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model 'ggml-vic13b-uncensored-q5_1.bin'
main: error: unable to load model

Thank you for the development, I hope this let me know if anything is needed.

**Comment by fredi-python** [comment]
This should now be fixed.

**Comment by uptogodown** [comment]
Hello,
I have just manually removed & reinstalled using all the commands listed and the issue is still here, I am on Linux  Mint 20.3 .

**Comment by fredi-python** [comment]
Did you remove the whole llama.cpp folder?

**Comment by fredi-python** [comment]
If your folder still exists navigate to it and run
```
git pull
```
Then run
```
make -j
```
And you should be able to load the model.

**Comment by fredi-python** [comment]
How is it going?
Did it work now?

**Comment by uptogodown** [comment]
No luck, did the commands and still says "unable to lad model":
~/llama.cpp$ ./main -m ggml-vic13b-uncensored-q5_1.bin -f 'prompts/chat-with-vicuna-v1.txt' -r 'User:' --temp 0.36
main: build = 732 (afd983c)
main: seed  = 1687442258
error loading model: failed to open ggml-vic13b-uncensored-q5_1.bin: No such file or directory
llama_init_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model 'ggml-vic13b-uncensored-q5_1.bin'
main: error: unable to load model

**Comment by uptogodown** [comment]
Please advise what OS(s) you are running it on that work.
Just if it helps I am using the 5.4.0-152-generic kernel

**Comment by fredi-python** [comment]
6.3.8-arch1-1
Arch Linux

**Comment by uptogodown** [comment]
Hi, I am still having the issues, I have latest Linux Mint 20.2 & tried on PopOS but I am still having the issue of being unable to load the model, tried reinstalling multiple times, git pull & make -j and still isn't working.
